name: Debug

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debug environment variables
      run: env

    - name: Whoami?
      run: id

    - name: list all binaries
      run: bash list-all-binaries.sh

    - name: PHP 7.1
      run: /usr/bin/php7.1 -v

    - name: PHP 7.2
      run: /usr/bin/php7.2 -v

    - name: PHP 7.3
      run: /usr/bin/php7.3 -v

    - name: PHP 7.4
      run: /usr/bin/php7.4 -v

    - name: Install Symfony binary
      run: |
          curl -sS https://get.symfony.com/cli/installer | bash; \
          sudo mv /home/runner/.symfony/bin/symfony /usr/local/bin/symfony;

    - name: Symfony binary version
      run: symfony version

    - name: List local PHP versions
      run: symfony local:php:list

    - name: Current PHP?
      run: php -v && php -i

    - name: What is current php?
      run: file `which php` && ls -al `which php`

    - name: Use PHP 7.3
      run: sudo update-alternatives --set php /usr/bin/php7.3 && php -v

    - name: MySQL version
      run: mysql --version

    - name: Docker info
      run: docker info

    - name: Install tree
      run: sudo apt-get install -y tree

    - name: Tree /var/lib/docker
      run: sudo tree /var/lib/docker

    - name: Disk Usage of /var/lib/docker
      run: sudo du -h /var/lib/docker


