name: Debug

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2

    - name: Debug environment variables
      run: env

    - name: Whoami?
      run: id

    - name: list all binaries
      run: |
          for p in ${PATH//:/ }; \
              do find $p -type f -executable; \
          done;
