name: PHP

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]

    steps:
    - name: Change PHP to PHP ${{ matrix.php }}
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

    - name: PHP version
      run: php -v

    - name: Install symfony CLI
      run: |
        curl https://get.symfony.com/cli/installer | bash
        echo "::add-path::${HOME}/.symfony/bin"

    - run: symfony local:php:list -vvv

    - name: PHP.ini
      run: php -i
