name: PHP

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]

    steps:
    - name: Change PHP to PHP ${{ matrix.php }}
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

    - name: PHP version
      run: php -v

    - name: Install symfony CLI
      run: |
        wget https://get.symfony.com/cli/installer -O installer
        chmod +x installer
        sudo ./installer --install-dir=/usr/local/bin
        rm -f installer

    - run: symfony local:php:list

    - name: PHP.ini
      run: php -i
